import { GoogleGenAI, Type } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export interface AnalysisResult {
  authenticityScore: number;
  aiProbability: number;
  humanProbability: number;
  analysis: string;
  linguisticPatterns: {
    perplexity: "Low" | "Medium" | "High";
    burstiness: "Low" | "Medium" | "High";
    consistency: "Low" | "Medium" | "High";
  };
  verdict: string;
}

export async function probeIntegrity(text: string): Promise<AnalysisResult> {
  if (!text || text.trim().length === 0) {
    throw new Error("Please provide some text for analysis.");
  }

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: `Analyze the following text to determine if it was generated by an AI or written by a human. 
    Focus on linguistic patterns like perplexity (randomness of word choice) and burstiness (variation in sentence structure).
    
    Text to analyze:
    """
    ${text}
    """`,
    config: {
      systemInstruction: "You are an expert linguistic analyst specializing in AI content detection. Provide a detailed analysis and a score from 0 to 100, where 100 means definitely human and 0 means definitely AI.",
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          authenticityScore: { type: Type.NUMBER, description: "0-100 score (100=Human, 0=AI)" },
          aiProbability: { type: Type.NUMBER, description: "0-100 probability of being AI" },
          humanProbability: { type: Type.NUMBER, description: "0-100 probability of being Human" },
          analysis: { type: Type.STRING, description: "Detailed linguistic analysis" },
          linguisticPatterns: {
            type: Type.OBJECT,
            properties: {
              perplexity: { type: Type.STRING, enum: ["Low", "Medium", "High"] },
              burstiness: { type: Type.STRING, enum: ["Low", "Medium", "High"] },
              consistency: { type: Type.STRING, enum: ["Low", "Medium", "High"] }
            },
            required: ["perplexity", "burstiness", "consistency"]
          },
          verdict: { type: Type.STRING, description: "Short final verdict" }
        },
        required: ["authenticityScore", "aiProbability", "humanProbability", "analysis", "linguisticPatterns", "verdict"]
      }
    }
  });

  const result = JSON.parse(response.text || "{}");
  return result;
}
