import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import { GoogleGenAI, Type } from "@google/genai";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // Gemini API Setup
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn("GEMINI_API_KEY is not set. API calls will fail.");
  }
  const ai = new GoogleGenAI({ apiKey: apiKey || "" });

  // API Routes
  app.post("/api/analyze", async (req, res) => {
    if (!apiKey) {
      return res.status(500).json({ 
        error: "Gemini API Key is missing. Please add GEMINI_API_KEY to your environment variables (e.g., in Vercel dashboard)." 
      });
    }
    try {
      const { text } = req.body;

      if (!text || text.trim().length < 50) {
        return res.status(400).json({ error: "Text is too short for meaningful analysis. Please provide at least 50 characters." });
      }

      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: [{
          role: "user",
          parts: [{
            text: `Analyze the following text to determine if it was generated by an AI or written by a human. 
            Focus on linguistic patterns like perplexity (randomness of word choice) and burstiness (variation in sentence structure).
            
            Text to analyze:
            """
            ${text}
            """`
          }]
        }],
        config: {
          systemInstruction: "You are an expert linguistic analyst specializing in AI content detection. Provide a detailed analysis and a score from 0 to 100, where 100 means definitely human and 0 means definitely AI.",
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              authenticityScore: { type: Type.NUMBER, description: "0-100 score (100=Human, 0=AI)" },
              aiProbability: { type: Type.NUMBER, description: "0-100 probability of being AI" },
              humanProbability: { type: Type.NUMBER, description: "0-100 probability of being Human" },
              analysis: { type: Type.STRING, description: "Detailed linguistic analysis" },
              linguisticPatterns: {
                type: Type.OBJECT,
                properties: {
                  perplexity: { type: Type.STRING, enum: ["Low", "Medium", "High"] },
                  burstiness: { type: Type.STRING, enum: ["Low", "Medium", "High"] },
                  consistency: { type: Type.STRING, enum: ["Low", "Medium", "High"] }
                },
                required: ["perplexity", "burstiness", "consistency"]
              },
              verdict: { type: Type.STRING, description: "Short final verdict" }
            },
            required: ["authenticityScore", "aiProbability", "humanProbability", "analysis", "linguisticPatterns", "verdict"]
          }
        }
      });

      const result = JSON.parse(response.text || "{}");
      res.json(result);
    } catch (error: any) {
      console.error("Gemini Error:", error);
      res.status(500).json({ error: error.message || "An error occurred during analysis." });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
